# Generated by Django 4.2.10 on 2024-07-09 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0003_alter_pedido_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocarrito',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_carrito', to=settings.AUTH_USER_MODEL),
        ),
    ]
